# Generated by Django 4.1.4 on 2022-12-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoImg',
        ),
    ]
