# Generated by Django 4.1.4 on 2022-12-27 03:01

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_videoimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image10',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image4',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image5',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image6',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image7',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image8',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image9',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='video',
            name='video1',
            field=models.FileField(default='one-off', upload_to='admin', validators=[home.validators.file_size]),
        ),
        migrations.AddField(
            model_name='video',
            name='video2',
            field=models.FileField(default='one-off', upload_to='admin', validators=[home.validators.file_size]),
        ),
        migrations.AddField(
            model_name='video',
            name='video3',
            field=models.FileField(default='one-off', upload_to='admin', validators=[home.validators.file_size]),
        ),
        migrations.AddField(
            model_name='video',
            name='video4',
            field=models.FileField(default='one-off', upload_to='admin', validators=[home.validators.file_size]),
        ),
        migrations.AddField(
            model_name='video',
            name='video5',
            field=models.FileField(default='one-off', upload_to='admin', validators=[home.validators.file_size]),
        ),
    ]
