# Generated by Django 4.1.4 on 2022-12-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_image_image_remove_video_video_image_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image11',
            field=models.ImageField(default='one-off', upload_to='img/%y'),
        ),
    ]
